version: '3'

services:
  video-app-backend-app:
    container_name: simplevideochatapp
    restart: always
    build: ./simplevideochatapp
    ports:
      - 4008:3000
    environment:
      - APP_PORT=3000

volumes:
  dbdata: